# Unified quick start helper generated by scripts/fix_connections.py
param(
    [string]$OrchestratorPath = "C:\Users\Inaki Senar\Documents\GitHub\AI-FACTORY-v2",
    [string]$AppPath = "C:\Users\Inaki Senar\Documents\GitHub\adaptive-sales-engine"
)

$ErrorActionPreference = "Stop"
Set-Location $OrchestratorPath
Write-Host "Starting ecosystem from $OrchestratorPath" -ForegroundColor Cyan

if (Test-Path "$OrchestratorPath\start_ecosystem.ps1") {
    & "$OrchestratorPath\start_ecosystem.ps1" -OrchestratorPath $OrchestratorPath -AppPath $AppPath
} else {
    Write-Host "start_ecosystem.ps1 was not found." -ForegroundColor Red
    exit 1
}
