"""Assemble the bilingual (ES/EN) INGETRANS Smart product report R3 (IGC-DW100 only).

- Spanish body: generated by build_ingetrans_smart_report_r2.build() and adjusted to the DW100-only
  commercial decision (CD-01) with explicit string replacements that are asserted to exist.
- English body: ingetrans_smart_report_r3_en.body_en().
- A fixed ES/EN switcher is added (screen only); print/PDF keeps the visible language.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import build_ingetrans_smart_report_r2 as r2  # noqa: E402
from ingetrans_smart_report_r3_en import body_en  # noqa: E402

OUTPUTS = [
    Path(r"C:\Users\isena\Documents\INGECART\MARKETING\ARTWORK\INGETRANS\INGETRANS_SMART_PRODUCT_REPORT_IGC-DW100_R3_ES-EN_2026-09-14.html"),
    Path(r"C:\Users\isena\Documents\GitHub\AI-FACTORY-v2\INGETRANS_SMART_PRODUCT_REPORT_IGC-DW100_R3_ES-EN_2026-09-14.html"),
]

ES_DW100_REPLACEMENTS = [
    ("<tr><td>Base técnica</td><td>Ruedas motrices IGC-DW20 / IGC-DW100 · navegación láser · 48 V CC LiFePO4</td><td>Sustituye a</td><td>Informe Smart 2026-09-10 (base JNOV)</td></tr>",
     "<tr><td>Base técnica</td><td>4 × ruedas motrices IGC-DW100 · navegación láser · 48 V CC LiFePO4</td><td>Sustituye a</td><td>Informe Smart 2026-09-10 (base JNOV) y R2 (DW20/DW100)</td></tr>"),
    ("IS-SMART-R2 · Rev. 2", "IS-SMART-R3 · Rev. 3"),
    ("la solera existente con ruedas motrices INGECART IGC-DW, navegación láser y batería embarcada.",
     "la solera existente con ruedas motrices INGECART IGC-DW100, navegación láser y batería embarcada."),
    ("El carro rueda sobre la solera existente con ruedas motrices <b>IGC-DW</b>, navega por láser",
     "El carro rueda sobre la solera existente con cuatro ruedas motrices <b>IGC-DW100</b>, navega por láser"),
    ('<td><span class="kpi-v">0,90 m/s</span><span class="kpi-l">Velocidad con IGC-DW20</span></td>',
     '<td><span class="kpi-v">0,43 m/s</span><span class="kpi-l">Velocidad con IGC-DW100</span></td>'),
    ("<td>Motor único sobre carril embebido, 80 m/min</td><td>Ruedas motrices IGC-DW sobre solera, 0,90 m/s (54 m/min) con DW20</td>",
     "<td>Motor único sobre carril embebido, 80 m/min</td><td>Cuatro ruedas motrices IGC-DW100 sobre solera, 0,43 m/s (26 m/min)</td>"),
    ("IGC-DW propias, control, seguridad funcional y conformidad bajo una única responsabilidad.",
     "IGC-DW100 propias, control, seguridad funcional y conformidad bajo una única responsabilidad."),
    ("<td>Ruedas de poliuretano IGC-DW sobre la solera existente; recorrido virtual en el mapa de navegación</td>",
     "<td>Ruedas de poliuretano IGC-DW100 sobre la solera existente; recorrido virtual en el mapa de navegación</td>"),
    ("<td>Cuatro conjuntos IGC-DW con tracción, dirección, freno y encóder integrados; intercambiables como unidad</td>",
     "<td>Cuatro conjuntos IGC-DW100 con tracción, dirección, freno y encóder integrados; intercambiables como unidad</td>"),
    ("<td>80 m/min (1,33 m/s)</td><td>0.90 m/s (54 m/min) con IGC-DW20 · 0.43 m/s con IGC-DW100</td>",
     "<td>80 m/min (1,33 m/s)</td><td>0,43 m/s (26 m/min) con IGC-DW100 — único modelo ofertado para bobinas</td>"),
    ("Una corrugadora de referencia consume 8,8 bobinas/h; está muy\npor debajo de ese umbral.",
     "En un corredor de 60 m a la velocidad del IGC-DW100 el umbral equivale a unas 20–25 misiones\nde bobina única por hora; una corrugadora de referencia consume 8,8 bobinas/h con viajes de doble bobina disponibles y queda por debajo."),
    ("<td>Servocontroladores 48 V CC con STO · CANopen CiA 301 / DS 402 · ruedas IGC-DW</td>",
     "<td>Servocontroladores 48 V CC con STO · CANopen CiA 301 / DS 402 · cuatro ruedas IGC-DW100</td>"),
    ("<p class=\"lead\">INGETRANS Smart es más lento en punta que el carro sobre carril. En cadencia efectiva la\ndiferencia es menor, porque el ciclo lo dominan las interfaces de recogida y entrega, no el traslado.\nPerfil trapezoidal; carril con rampas de 4,5 s, Smart con aceleración de 0,30 m/s²; 6 s + 6 s de interfaz.</p>",
     "<p class=\"lead\">INGETRANS Smart es más lento en punta que el carro sobre carril. En cadencia efectiva la\ndiferencia es menor, porque el ciclo lo dominan las interfaces de recogida y entrega y los viajes de doble bobina,\nno solo el traslado. Perfil trapezoidal; carril con rampas de 4,5 s, Smart con aceleración de 0,30 m/s²; 6 s + 6 s de interfaz.</p>"),
    ("INGETRANS Smart (0,90 m/s, IGC-DW20)", "INGETRANS Smart (0,43 m/s, IGC-DW100)"),
    ("≈ 16 s</td>", "≈ 29 s</td>"),
    ("≈ 32 s</td>", "≈ 62 s</td>"),
    ("≈ 36 s</td>", "≈ 71 s</td>"),
    ("≈ 70 s</td>", "≈ 141 s</td>"),
    ("<td>≈ 66 s (≈ 54 misiones/h)</td><td>≈ 85 s (≈ 42 misiones/h)</td></tr>",
     "<td>≈ 66 s (≈ 54 misiones/h)</td><td>≈ 154 s (≈ 23 misiones/h)</td></tr><tr><td>Misión completa 60 m ida y vuelta con recogida y entrega</td><td>≈ 111 s (≈ 32 misiones/h)</td><td>≈ 294 s (≈ 12 misiones/h)</td></tr>"),
    ('<td><span class="kpi-v">&lt; 25 %</span><span class="kpi-l">Utilización del carro Smart a 30 m</span></td>',
     '<td><span class="kpi-v">&lt; 40 %</span><span class="kpi-l">Utilización del carro Smart a 30 m, bobina única</span></td>'),
    ('<td><span class="kpi-v">≈ 60/h</span><span class="kpi-l">Umbral donde el carril gana</span></td>',
     '<td><span class="kpi-v">≈ 20–25/h</span><span class="kpi-l">Misiones de bobina única donde el carril gana a 60 m</span></td>'),
    ("tiempo de misión Smart quedan por debajo del 60 % del tiempo disponible. El estudio de aplicación simula el\nciclo real de la planta con el gemelo digital INGECART y entrega las bobinas/hora que se pueden esperar.",
     "tiempo de misión Smart quedan por debajo del 60 % del tiempo disponible. Con viajes de doble bobina el número de\nmisiones se reduce aproximadamente a la mitad. El estudio de aplicación simula el ciclo real de la planta con el gemelo\ndigital INGECART y entrega las bobinas/hora que se pueden esperar; si la cifra no cubre la demanda, se recomienda\nINGETRANS con carril o una segunda unidad Smart."),
    ("<p class=\"note\">Por encima de 10 t de masa total la velocidad se limita a 0,43 m/s (IGC-DW100) por criterio de\nestabilidad de la carga:",
     "<p class=\"note\">La velocidad se limita deliberadamente a 0,43 m/s con IGC-DW100 por criterio de\nestabilidad de la carga:"),
    ("<td>Rueda IGC-DW intercambiable como unidad embridada; batería (año 7–10); bandas; ópticas</td>",
     "<td>Rueda IGC-DW100 intercambiable como unidad embridada; batería (año 7–10); bandas; ópticas</td>"),
    ("En punta sí: 0,90 m/s frente a 80 m/min (1,33 m/s). En cadencia efectiva la diferencia es menor porque el ciclo lo dominan las interfaces de recogida y entrega. A 8,8 bobinas/h la utilización del carro queda por debajo del 25 %.",
     "En punta sí: 0,43 m/s frente a 80 m/min (1,33 m/s). En cadencia efectiva la diferencia es menor porque el ciclo lo dominan las interfaces de recogida y entrega y los viajes de doble bobina reducen las misiones a la mitad. A 8,8 bobinas/h con doble bobina la utilización del carro queda por debajo del 25 %."),
    ("Gama de ruedas IGC-DW20 / IGC-DW100</td><td>Validado</td>", "Rueda motriz IGC-DW100</td><td>Validado</td>"),
    ("<td>Margen de tracción 1,91 reproducido</td>", "<td>Margen de tracción 1,91 reproducido; ≈ 8 para un chasis portabobinas de 8 t</td>"),
    ("Configuración de ruedas para chasis portabobinas INGETRANS</td><td>Pendiente</td><td>4 × IGC-DW20 (≤ 6 t) o 4 × IGC-DW100 según matriz de bobinas y tara del chasis</td>",
     "Configuración de ruedas para chasis portabobinas INGETRANS</td><td>Decidido</td><td>Solo 4 × IGC-DW100 (decisión comercial CD-01, 14/09/2026); IGC-DW20 no se oferta para bobinas</td>"),
    ("<td>Gemelo digital sobre layout aprobado (0,90 m/s, aproximación 0,30 m/s)</td>",
     "<td>Gemelo digital sobre layout aprobado (0,43 m/s, aproximación 0,30 m/s, cuota de doble bobina)</td>"),
    ("<td>Escandallo de producto; en Paige se oferta al mismo EXW que INGETRANS carril</td>",
     "<td>Escandallo de producto; en Paige se oferta con −5 % equipo, −15 % servicios y −80 % obra civil del cliente frente a INGETRANS carril</td>"),
    ("<b>Nota de revisión.</b> Esta revisión R2 sustituye la base técnica del informe del 10/09/2026, que se apoyaba en\nmódulos de tracción de tercero (JNOV MDS/DDW-4TP, 2 km/h, guiado por línea DataMatrix, cuasi-máquina). La base\nvigente es la familia de ruedas motrices propias IGC-DW, navegación láser con referencia de estación, batería\nLiFePO4 48 V y marcado CE de máquina completa por INGECART.",
     "<b>Nota de revisión.</b> Esta revisión R3 sustituye al informe del 10/09/2026 (módulos de tracción de tercero JNOV\nMDS/DDW-4TP, 2 km/h, guiado por línea DataMatrix, cuasi-máquina) y a la R2 del 14/09/2026, que aún contemplaba la\nIGC-DW20 para bobinas. La base vigente es cuatro ruedas motrices propias IGC-DW100, navegación láser con referencia\nde estación, batería LiFePO4 48 V y marcado CE de máquina completa por INGECART."),
    ("de 2 a 40 toneladas de masa total.</p>", "de 2 a 40 toneladas de masa total; <b>para INGETRANS Smart solo se oferta la IGC-DW100.</b></p>"),
    ("<th>IGC-DW20</th><th>IGC-DW100</th>", "<th>IGC-DW20 (no ofertada para bobinas)</th><th>IGC-DW100 (INGETRANS Smart)</th>"),
    ("<td>Palet europeo, bobinas ligeras, cajas. Tracción diferencial con giro sobre el propio eje.</td>",
     "<td>Palet europeo, bobinas ligeras, cajas. No aplicable a INGETRANS Smart.</td>"),
    ("<td>Plataforma 4 × 2 m con tracción y dirección en las cuatro esquinas. <b>Configuración de referencia para el chasis portabobinas INGETRANS Smart.</b></td>",
     "<td>Plataforma 4 × 2 m con tracción y dirección en las cuatro esquinas. No aplicable a INGETRANS Smart.</td>"),
    ("<td>Bobinas de gran formato, dobles bobinas pesadas, utillajes. Velocidad reducida a 0,43 m/s por estabilidad de carga.</td>",
     "<td><b>Chasis portabobinas INGETRANS Smart</b> (bobina única o doble < 3.500 kg cada una más tara, ≈ 8.000 kg), bobinas de gran formato, utillajes. Velocidad limitada a 0,43 m/s por estabilidad de carga.</td>"),
    ("Rev. 2 — 14/09/2026. Sustituye al informe INGETRANS Smart del\n10/09/2026.</p>",
     "Rev. 3 — 14/09/2026. Sustituye a los informes INGETRANS Smart del\n10/09/2026 y R2.</p>"),
]

SWITCHER_CSS = """
<style>
.lang.hidden { display: none; }
.lang-switch { position: fixed; top: 10mm; right: 6mm; z-index: 100; display: flex; gap: 2px; background: #111; padding: 2px; border-radius: 3px; }
.lang-switch button { font-family: Arial, Helvetica, sans-serif; font-size: 8pt; font-weight: bold; letter-spacing: 1pt; color: #ddd; background: transparent; border: 0; padding: 2.2mm 3.4mm; cursor: pointer; text-transform: uppercase; }
.lang-switch button.active { background: #FF6304; color: #fff; }
@media print { .lang-switch { display: none; } }
</style>
"""

SWITCHER_HTML = """
<div class="lang-switch" role="tablist" aria-label="Idioma / Language">
  <button type="button" class="active" data-language="es" aria-pressed="true">ES</button>
  <button type="button" data-language="en" aria-pressed="false">EN</button>
</div>
"""

SWITCHER_JS = """
<script>
(function () {
  var buttons = document.querySelectorAll('[data-language]');
  var blocks = document.querySelectorAll('.lang');
  function apply(lang) {
    blocks.forEach(function (b) { b.classList.toggle('hidden', !b.classList.contains('lang-' + lang)); });
    buttons.forEach(function (btn) {
      var on = btn.dataset.language === lang;
      btn.classList.toggle('active', on);
      btn.setAttribute('aria-pressed', String(on));
    });
    document.documentElement.setAttribute('lang', lang);
    try { localStorage.setItem('ingetrans_smart_report_lang', lang); } catch (e) {}
  }
  buttons.forEach(function (btn) { btn.addEventListener('click', function () { apply(btn.dataset.language); }); });
  var saved = null;
  try { saved = localStorage.getItem('ingetrans_smart_report_lang'); } catch (e) {}
  var fromQuery = (location.search.match(/[?&]lang=(es|en)/) || [])[1];
  apply(fromQuery || saved || 'es');
})();
</script>
"""


def main() -> None:
    baseline = json.loads(r2.BASELINE.read_text(encoding="utf-8"))
    full_es = r2.build(baseline)

    head_end = full_es.index("<body>") + len("<body>")
    head = full_es[:head_end]
    body_es = full_es[head_end:full_es.rindex("</body>")]

    # drop the Spanish screen note (kept once, bilingual, below)
    body_es = re.sub(r'<div class="screen-note">.*?</div>\s*', "", body_es, count=1, flags=re.S)

    missing = [old[:70] for old, new in ES_DW100_REPLACEMENTS if old and old not in body_es]
    if missing:
        raise SystemExit("Spanish anchors not found:\n  " + "\n  ".join(missing))
    for old, new in ES_DW100_REPLACEMENTS:
        if old:
            body_es = body_es.replace(old, new)
    if "DW20" in body_es.replace("IGC-DW20 (no ofertada para bobinas)", "").replace("IGC-DW20 no se oferta", "").replace("R2 (DW20/DW100)", "").replace("la\nIGC-DW20 para bobinas", ""):
        leftovers = [m.start() for m in re.finditer("DW20", body_es)]
        print("warning: DW20 mentions remain at", leftovers[:10])

    logo = r2.embedded_logo()
    cover = r2.embedded_cover_image()
    body_en_html = body_en(logo, cover)

    head = head.replace("<title>INGECART · INGETRANS Smart — Informe técnico de producto R2</title>",
                        "<title>INGECART · INGETRANS Smart — Informe técnico de producto R3 / Technical product report R3</title>")
    head = head.replace("</head>", SWITCHER_CSS + "</head>")

    screen_note = """
<div class="screen-note">
<b>Vista previa en navegador / Browser preview.</b> Use el selector ES/EN de la esquina superior derecha. El PDF
imprime el idioma visible; la banda de cabecera y el pie corporativo los aplica el motor de maquetación.
Use the ES/EN switch in the top-right corner; the PDF prints the visible language.
</div>
"""
    html = (
        head
        + SWITCHER_HTML
        + screen_note
        + '\n<div class="lang lang-es">\n' + body_es + "\n</div>\n"
        + '<div class="lang lang-en hidden">\n' + body_en_html + "\n</div>\n"
        + SWITCHER_JS
        + "</body>\n</html>\n"
    )
    for out in OUTPUTS:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(html, encoding="utf-8")
        print("written", out, len(html))


if __name__ == "__main__":
    main()
